/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.6.4/userguide/multi_project_builds.html
 */

rootProject.name = "ballista-jvm"

// Ballista JVM Query Engine
include("datatypes")
include("datasource")
include("logical-plan")
include("optimizer")
include("physical-plan")
include("query-planner")
include("sql")
include("execution")
include("protobuf")
include("executor")
include("fuzzer")

include("benchmarks")
include("examples")

// Ballista JVM Connectors
include("client")
include("jdbc")


