apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-aggregate
spec:
  template:
    spec:
      containers:
        - name: parallel-aggregate
          image: ballistacompute/parallel-aggregate
      restartPolicy: Never
  backoffLimit: 4